# Data preparation

In [1]:
import numpy as np
import pandas as pd

import math
from time import time
from copy import deepcopy, copy

In [2]:
folder_path = "databases/avocado/"
path = folder_path+"avocado.csv"
document = pd.read_csv(path)

In [3]:
doc  = document[["Date", "region", "type", "AveragePrice"]].sort_values(by="Date")
data = doc.to_numpy()
np.save(folder_path+"raw_avocado.npy", data, allow_pickle=True)
data

array([['2015-01-04', 'Southeast', 'organic', 1.75],
       ['2015-01-04', 'Chicago', 'organic', 1.49],
       ['2015-01-04', 'HarrisburgScranton', 'organic', 1.68],
       ...,
       ['2018-03-25', 'SouthCentral', 'organic', 1.42],
       ['2018-03-25', 'California', 'organic', 1.7],
       ['2018-03-25', 'NewYork', 'conventional', 1.34]], dtype=object)

In [4]:
dates, dates_count = np.unique(data[:,0], return_counts=True)
state, state_count = np.unique(data[:,1], return_counts=True)
types, types_count = np.unique(data[:,2], return_counts=True)

In [5]:
result = np.zeros((dates.shape[0],state.shape[0],types.shape[0]))-2137
result

array([[[-2137., -2137.],
        [-2137., -2137.],
        [-2137., -2137.],
        ...,
        [-2137., -2137.],
        [-2137., -2137.],
        [-2137., -2137.]],

       [[-2137., -2137.],
        [-2137., -2137.],
        [-2137., -2137.],
        ...,
        [-2137., -2137.],
        [-2137., -2137.],
        [-2137., -2137.]],

       [[-2137., -2137.],
        [-2137., -2137.],
        [-2137., -2137.],
        ...,
        [-2137., -2137.],
        [-2137., -2137.],
        [-2137., -2137.]],

       ...,

       [[-2137., -2137.],
        [-2137., -2137.],
        [-2137., -2137.],
        ...,
        [-2137., -2137.],
        [-2137., -2137.],
        [-2137., -2137.]],

       [[-2137., -2137.],
        [-2137., -2137.],
        [-2137., -2137.],
        ...,
        [-2137., -2137.],
        [-2137., -2137.],
        [-2137., -2137.]],

       [[-2137., -2137.],
        [-2137., -2137.],
        [-2137., -2137.],
        ...,
        [-2137., -2137.],
        [-2137.

In [6]:
for [date, city, typ, price] in data:
    date_id = np.where(dates==date)[0][0]
    city_id = np.where(state==city)[0][0]
    type_id = np.where(types==typ)[0][0]
    result[date_id][city_id][type_id] = price

In [9]:
print(np.where(result<=0))
np.save(folder_path+"avocado_arr.npy", result)
np.where(np.load(folder_path+"avocado_arr.npy")<0)

(array([ 48, 128, 129], dtype=int64), array([53, 53, 53], dtype=int64), array([1, 1, 1], dtype=int64))


(array([ 48, 128, 129], dtype=int64),
 array([53, 53, 53], dtype=int64),
 array([1, 1, 1], dtype=int64))

In [12]:
np.save(folder_path+"avocado_dates.npy", dates)
np.save(folder_path+"avocado_regions.npy", state)
np.save(folder_path+"avocado_types.npy", types)
np.save(folder_path+"avocado_columns", np.array(["Date", "Region", "Type", "Price"]))